### ISSUE TITLE
When getting an unauthorized error on clicking connect, no error displayed, and nothing happens

### ISSUE THREAD

**Issue by nomex26** [zabo-api/zabo-nodejs-quickstart-app#6]
**Problem**
When I follow the quickstart guide and launch the app, I get an unauthorized error (due to an invalid API key, I guess). The problem is, when clicking the "connect" button, nothing happens, and the only way to find out is to open up the dev tools and look at the network tab to see the failed request.

**Proposed solution**
It would be good to have some kind of error message pop up here so it doesn't just seem like the button does nothing.

**Comment by dreinke** [comment]
Brave issue due to their cookies policy. We will investigate.
