### ISSUE TITLE
"HMAC sig timestamp is from the future!"

### ISSUE THREAD

**Issue by ryancwalsh** [zabo-api/zabo-nodejs-quickstart-app#9]
I'm trying to run a freshly installed zabo-api/zabo-nodejs-quickstart-app.

I'm using my sandbox CLIENT_ID, PUBLIC_API_KEY, and SECRET_API_KEY.

I ran `npm start`, and it opens the browser to a page that says:

> {"message":"HMAC sig timestamp is from the future!"}

I ran `date`, and my system's time is correct. How can I fix whatever the problem is?

**Comment by ryancwalsh** [comment]
I've spent many hours trying to get Zabo to work at all, and I've had no luck. 

Can you please confirm that the Zabo API is still working and not defunct?

This is the error I'm getting when trying to run your quickstart-app:

```error: s [Error]: HMAC sig timestamp is from the future!
      at e.exports.request (/code/zabo-nodejs-quickstart-app/node_modules/zabo-sdk-js/dist/index.js:20:24407)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async e.exports.connect (/code/zabo-nodejs-quickstart-app/node_modules/zabo-sdk-js/dist/index.js:20:23388)
      at async Object.init (/code/zabo-nodejs-quickstart-app/node_modules/zabo-sdk-js/dist/index.js:20:21200)
      at async Object.init (/code/zabo-nodejs-quickstart-app/node_modules/zabo-sdk-js/dist/index.js:20:20046)
      at async /code/zabo-nodejs-quickstart-app/routes/index.js:62:20 {
    error_type: 400,
```

Thank you for your help. I'll be very excited to get Zabo working.

**Comment by dreinke** [comment]
Hey @ryancwalsh! yeah, Zabo API is fully working.
I just ran the quickstart from a fresh install (mac os, chrome and node v14.15.4) and I was not able to reproduce the error you mentioned. Could you pls provide more info about your environment?
If you are getting a `request_id` in the response body, it would help too.
I also encourage you to join us in our [chat](https://zabo.com/discord), where we daily help devs with issues like that.

**Comment by ryancwalsh** [comment]
@dreinke Thanks for your response. I'm looking forward to us figuring this out since Zabo looks really useful.

I'm on a Windows 10 machine, and usually I develop within WSL 1 Ubuntu (https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).

I got:

```
error_type: 400,
request_id: 'b328e51d-9075-480f-ba25-53101c54198c'

```

Then I also tried _not_ using WSL and just using Win 10 command prompt as admin:

```
error_type: 400,
request_id: '683bf7bc-dbee-47b5-8eee-db5404038a76'
```

**Comment by dreinke** [comment]
Thanks for the info!
The timestamp we are receiving from your request is slightly ahead of time. We have a leeway to deal with this kind of situation, but it seems that it was not enough in your case.
We will investigate and follow up here asap.

**Comment by ryancwalsh** [comment]
@dreinke Yeah it sounded like that would be the problem, but I can't think of why, given that nowadays clocks are always synced. I see that my Windows 10 automatically syncs via time.windows.com. I'll be interested to hear what you figure out today.

**Comment by dreinke** [comment]
Should be working now, @ryancwalsh.
These sync issues are pretty common actually and that's why we operate in a time window.
Your delta timestamp was close to 100ms (ahead) and we were not expecting that much. Now you should be good until 1s.

**Comment by ryancwalsh** [comment]
@dreinke It works without error now: I get a 200 result, and the page shows:

> Zabo Quickstart App
> Welcome to the Zabo Quickstart App!
> First let's connect a wallet by clicking the connect button below

I'm excited to explore this app and the API docs later! Thank you!

**Comment by ryancwalsh** [comment]
Hi @dreinke , Zabo was working for me yesterday, but when I started using it again about an hour ago, I started seeing this problem happening again:

```
init failed: 400 HMAC sig timestamp is from the future! {
api |   error: s [Error]: HMAC sig timestamp is from the future!
api |       at e.exports.request (/mnt/c/code/investments/node_modules/zabo-sdk-js/dist/index.js:20:25092)
api |       at processTicksAndRejections (internal/process/task_queues.js:93:5)
api |       at e.exports.connect (/mnt/c/code/investments/node_modules/zabo-sdk-js/dist/index.js:20:24073)
api |       at Object.init (/mnt/c/code/investments/node_modules/zabo-sdk-js/dist/index.js:20:21885)
api |       at Object.init (/mnt/c/code/investments/node_modules/zabo-sdk-js/dist/index.js:20:20732)
api |       at initZabo (/mnt/c/code/investments/api/src/functions/zabo.ts:18:12)
api |       at createResponse (/mnt/c/code/investments/api/src/functions/zabo.ts:35:18)
api |       at requestHandler (/mnt/c/code/investments/node_modules/@redwoodjs/dev-server/dist/requestHandlers/awsLambda.js:145:29)
api |       at lambdaHandler (/mnt/c/code/investments/node_modules/@redwoodjs/dev-server/dist/http.js:69:5) {
api |     error_type: 400,
api |     request_id: '5844b8b7-8386-45b8-a167-2c693981ae0a'
api |   }
api | }
```

My Windows 10 automatically syncs its clock via time.windows.com. And I'm using WSL. When I run `date`, the output looks good.

**Can you please check whether there is a problem on your end?**

Thanks!

**Comment by ryancwalsh** [comment]
As mentioned in the https://discord.com/channels/533336922970521600/607688477747707905 chat with you, what I just tried was: I switched my Windows 10 to no longer set its clock automatically, then I set its time to 1 minute behind, and then I tried my Zabo command again and got:
```
init failed: 400 HMAC sig timestamp expired longer than 30 seconds ago. {
api |   error: s [Error]: HMAC sig timestamp expired longer than 30 seconds ago.
```

But then once I set Windows 10 back to automatic sync, Zabo is now working again!
